# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=200)),
                ('Course_semester', models.CharField(choices=[('7F', '2017Fall'), ('7U', '2017Summer'), ('8S', '2018Spring')], default='7F', max_length=2)),
                ('Course_student', models.CharField(choices=[('SEIEE', 'School of Electronic Information and Electrical Engineering')], default='SEIEE', max_length=10)),
                ('Course_introduction', models.CharField(default='The lazy gay leave nothing there.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='theUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('S', 'student'), ('T', 'teacher')], default='S', max_length=1)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_course', models.ManyToManyField(to='class_management.Course')),
            ],
        ),
    ]
