# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_student',
            new_name='Course_school',
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_introduction',
            field=models.CharField(default='The lazy guy leave nothing there.', max_length=1000),
        ),
    ]
